language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn test
secure: "AHuHETRugGPI3pyQdmP0+zlRf4hf7AUnRBKW9A1sDu04GleeB0LgitV9f3l8p8qbtjyjHU5TMQbzULq2flZi2BwX68JObbYF5HffgUPB8oMd98xnzbihJDzjCuXUzXGXbk+Vt7yPujazSD1a8YlbaV2G2MBwyjdSfPR2/dAcDE1kSx5nk6mG1NZFRd/+QCjqrgGUrjFraizx/hMIFbPmrBo7ciQhjBCG7P2Fu88UgyaiBzTt1ixddp3BiSNxVGjnmGM/UzxhXzEm9t8siEBtdvwoskSG4Dgtqd31Nay2ipO+UCnoMCSuWXshhWvwmiaAwRbHdx3OShE1n8JXpG8TGmZjKF6AOgL7118XOgPbg380fcQbVzwKMbuH2sdnyqRPksB5S2/rZ2uOoebzSHLMquBIQ5I6PY7/4DOo1wkKMEU8ZKSxLt5jmNBAu32fkXqh5Ufwbr2cgraerKZEa75zWfsMRSeU2JVi/8SV4hT4wQjVzQqcBQ/YAtd0W+SLEnSqmkm1VDs1lCkkt1PSZqZt54XVFaJ4WdT0RvMIzJ3Lh/yBysMEEymrWVNrptHVAU1epT7Bi21bvrg6Dod0hHV076+vi7W46b7YdMrHyMDK2h4bSO5BZRRwkfELOOCpuKeuSVZThfR5kkerU5GVYVQ5K2tjmv44L003zdAuMS2utRw="
