language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn test
env:
  global:
    secure: qzpMck4/kEr+fWKDH/iKo0vdIthqZARSufuGrVT9AIx0j5XjloFZOhRiDht7q+S289IOtn1m2OCjtsvOXfmztlDKr2DCDWnYHvMAFBNIZ7kf091lKjjlxrEWt28mzxYgs3sDbGZbo47fuXbus+VKPpXsM6PwusypvQuPcdB3pkXUM2XhpbHmWRZ3IHPUNTw9doulni/dsjBlTajafb5mJLll2dt+oaftpjRyMIC3ZXjgRry7E2ALWZyRCCXK7BNHF/+vxkw4QpQ5JoBV1YWi5ICL0vXX3UR23G786IpBjssLvswxn3HM70qV0tu5qRmL4qMq8gGE2WTftO05xQUsYRZix9KgyG2pSf0sIdNeSeejdzSU0FLnYeXv5lTdcW3S5HDqmevTILg6CZGedvuw4GG2XtAdfukHfCZMIiCHehevH/4Ku3oTwiCRNPIBFAq17xdF4rAyGqzQlJAaLccFRJgN+XnpbqZZ/O1hSYLkvmqDbyVixt3ylWM5sC0TrXlwTtI4pO5XfCKVPff7YhlMz+oJZSWUXHqODTsgMveIlx8WPyzJW0OcYAK61Knp7KfYAJ6lAjXviPCdqaCqN3N+ezTNmvT1YSEVQRxQYPgd54+CRAf14Z/gegrWPu5nlYAZxfkMrT7FsSTCc1d3/dScN1059emXkCvPYkMKJJ/NPz4=
